### PR TITLE
Add attributewhitelist to support e.g. R&S+Sirtfi

### PR DESCRIPTION
**Pull request by msalle**
In order to whitelist IdPs based on the combination of e.g. R&S and Sirtfi, we introduce a new `attributewhitelist` source, which is similar to the standard `blacklist` and `whitelist` except we have multi-level arrays. See for example https://github.com/rcauth-eu/aarc-ansible-wayf/blob/master/roles/simplesamlphp/templates/config_patch/config_config-metarefresh.php.patch.j2#L26_L51

### CODE REVIEW

**Comment by tvdijen** [comment]
Great stuff! Just a few Psalm-issues left

**Comment by msalle** [comment]
> I've triggered a rebuild and there's one issue:
> 
>     1. SimpleSAML\Test\Module\metarefresh\MetaLoaderTest::testAttributewhitelist
> 
> 
> Undefined variable: metadata
> 
> /home/travis/build/simplesamlphp/simplesamlphp-module-metarefresh/tests/lib/MetaLoaderTest.php:139

Ok that's fixed (I was a bit too quick on that one, my apologies for wasting your time). I've added two more tests to test in total 3 different attributewhitelist scenarios. The built passes all tests.

**Comment by tvdijen** [comment]
Not all.. A few were hidden, but since they are caused by this PR I'd like to see them taken care of as well.. I can help if necessary

**Comment by tvdijen** [comment]
@thijskh Are you satisfied regarding the docs?

**Comment by tvdijen** [comment]
Are we cool with backporting this to 0.9?  Considering the changes, I am fine with it..

**Comment by thijskh** [comment]
Is there someone that wants/needs that?

**Comment by msalle** [comment]
For how long is the 0.9 still going to be the one shipped with the latest stable simplesamlphp?
In principle there are more people in the NRENs and European research communities that do filtering based on entity-attributes, but they might all already have their own patch (like we did).

**Comment by tvdijen** [comment]
0.9 is going to be there for a while.. The 1.0 branch is targeted at SimpleSAMLphp 2.0, which is not going to happen any time soon..

I mean, I can tag 0.10 if we strictly follow semver, but given the changes in this PR that would probably be overkill

**Comment by NicolasLiampotis** [comment]
> Is there someone that wants/needs that?

It would be really useful if the attribute based entity filtering was available upstream before SSP 2.0, so yes please :-)

**Comment by thijskh** [comment]
Then GO!

**Pull request merged**
